apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snorlx.fullname" . }}-secrets
  labels:
    {{- include "snorlx.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
  github-app-id: {{ .Values.github.appId | b64enc | quote }}
  github-client-id: {{ .Values.github.clientId | b64enc | quote }}
  github-client-secret: {{ .Values.github.clientSecret | b64enc | quote }}
  github-private-key: {{ .Values.github.privateKey | b64enc | quote }}
  github-webhook-secret: {{ .Values.github.webhookSecret | b64enc | quote }}
  session-secret: {{ default (randAlphaNum 32) .Values.session.secret | b64enc | quote }}

